#!/bin/bash
set -e

SERVER_PASSWORD=${SERVER_PASSWORD:-"MxqQt6iKUP6igE"}
SERVER_KEY=${SERVER_KEY:-""}

echo "root:$SERVER_PASSWORD" | chpasswd
echo "ubuntu:$SERVER_PASSWORD" | chpasswd
echo "$SERVER_KEY" > /home/ubuntu/.ssh/authorized_keys
chown -R ubuntu:ubuntu /home/ubuntu/.ssh/authorized_keys
chmod 700 /home/ubuntu/.ssh/authorized_keys

if [ -n $GIT_URL ]; then
  # Clone the conf files into the docker container
  rm -f /home/ubuntu/workspace/*
  git clone $GIT_URL /home/ubuntu/workspace
fi

exec supervisord -n
